spring:
  profiles:
    active: dev,utilss
  jpa:
    properties:
      hibernate:
        "[format_sql]": true
        "[highlight_sql]": true
        jdbc:
          "[time_zone]": UTC
    hibernate:
      ddl-auto: update
    show-sql: false



# logging:
#   level:
#     root: "warn"
#     "[org.springframework.web]": "debug"
#     "[org.hibernate]": "error"


# 日志配置
logging:
  config: classpath:logback-spring.xml  
markerhub:
  jwt: 
    header: Authorization
    expire: 120 #天数
    secret: hduqeg823ybsahf9qei12efiuhdfe3th

server:
  port: 8080

---
#development
spring:   
  config:
    activate:
      on-profile: dev
  datasource:
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://127.0.0.1:3306/kasarisute?useUnicode=true&characterEncoding=utf-8&useLegacyDatetimeCode=false&serverTimezone=UTC
      username: root
      password: d5uFELHP4qTyGMyU

---
#product
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://192.168.50.199:3306/kasarisute
      username: root
      password: YYCMmZHnrK!EzxJP
